### ISSUE TITLE
Error in reading info after first reset of the device

### ISSUE THREAD

**Issue by gg37263** [jiminghe/Xsens-MTi-1-Series-I2C-with-Raspberry-Pi-5#1]
When I am running the script I get an error, "Error writing opcode 4" which is in the MTSSP_DRIVER_I2C.cpp specifically the read function. Sometimes it will freeze up, get an i2c transfer timeout error, or eventually recover. Is there a specific timing requirement that needs to be met or a way to make the startup more consistent to be successful?

**Comment by jiminghe** [comment]
> When I am running the script I get an error, "Error writing opcode 4" which is in the MTSSP_DRIVER_I2C.cpp specifically the read function. Sometimes it will freeze up, get an i2c transfer timeout error, or eventually recover. Is there a specific timing requirement that needs to be met or a way to make the startup more consistent to be successful?

Hi,
I changed the code to use hardware reset, please connect the GPIO27 to the reset pin of the MTi-3-DK and run this code again.
